server:
  port: 10001 # 网关端口

spring:
  application:
    name: gatewayService
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  cloud:
    nacos:
      server-addr: 47.109.51.114:8848 # localhost:8848
    openfeign:
      httpclient:
        enabled: true
        max-connections: 200 #最大连接数
        max-connections-per-route: 50
    loadbalancer:
      eager-load:
        clients:
          - userService
          - remindService
          - contentService
          - commentService
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8081"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000

      routes:
        - id: login-service
          uri: lb://loginService
          predicates:
            - Path=/login/**

        - id: user-service
          uri: lb://userService
          predicates:
            - Path=/user/**

        - id: content-service
          uri: lb://contentService
          predicates:
            - Path=/content/**

        - id: comment-service
          uri: lb://commentService
          predicates:
            - Path=/comment/**

        - id: remind-service
          uri: lb://remindService
          predicates:
            - Path=/remind/**,/websocket/**,/chat/**

#        - id: user-service
#            uri: lb://userService
#            predicates:
#              - Path = /user/**

tofu:
  filter:
    routesWhitelist:
      - /login/loginByPwd
      - /login/loginByVfc
      - /login/sendRegisterVfc
      - /login/sendLoginVfc
      - /login/register
      - /content/getContent
      - /content/getCardInfo
      - /content/getContentDetail
      - /content/getTypeList
      - /comment/getComments


