server:
  port: 9003

spring:
  application:
    name: commentService
  cloud:
    nacos:
      server-addr: 47.109.51.114:8848 # localhost:8848 #localhost:8848 #47.109.51.114:8848
    openfeign:
      httpclient:
        enabled: true
        max-connections: 200 #最大连接数
        max-connections-per-route: 50
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tofu?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: lz020308

    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validation-query: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true

      # 如果允许时报错 java.lang.ClassNotFoundException: org.apache.log4j.Priority
      # 则导入 log4j 依赖即可
      # 配置监控统计拦截的filters, stat：监控统计、log4j：日志记录、wall:防御sql注入
      filters: stat,wall,log4j
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergesql=true;druid.stat.slowSqlMillis=500
      # 监控页面账号密码
      stat-view-servlet:
        login-username: zlee_tofu
        login-password: tofu123

mybatis-plus:
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl